add-search-sort-pagination-to-probe-display
jenkins-infra/plugin-health-scoring pull request #222
Opened 2023-02-25 18:03 UTC by lzeee

### History background
It's an old issue https://github.com/jenkins-infra/plugin-health-scoring/issues/65,  which has been placed for several months and labled as help-wanted. What I have done is just trying to add the necessary packages to the system and make it work. And **90% of the codes comes from 2 historical PR** made by https://github.com/jenkins-infra/plugin-health-scoring/pull/109 @dheerajodha and https://github.com/jenkins-infra/plugin-health-scoring/pull/194 @impact-maker. Thanks for the efforts and the valuable historical code review comments @alecharp .

### Description
This PR give the probe table abilities to perform operations such as sorting the probes by order,  seach probes by any attribute. In order to accomplish this goal, I mainly did 2 things on the historical code:
1. add 3 npm packages(datatables.net、jquery、expose-loader) and make them work.
2. add 4 *.less files to control the style of 4 added component, which is supplied by datatables.net.

![show](https://user-images.githubusercontent.com/21041025/221372344-605a2367-f12a-419e-9029-19e5823893f9.gif)

### Todo
I rarely wrote front-end code. So I really really need help and code reivew to improve these codes. I think there are som points need to be further discussed to get it done.
1. The style of newly added component is really ugly, which require adjustments.
2. The documentation need improve.
3. This ability is actually general. It can be directly extended to all other tables if necessary.

### Submitter checklist
- [ ] The description of this pull request is detailed and explain why this pull request is needed
- [ ] The changeset is on a specific branch
  - `feature/` for new feature, or improvements
  - `fix/` for bug fixes
  - `docs/` for any documentation changes
- [ ] If required, the documentation has been updated
- [ ] There is automated tests to cover the code change / addition
    - If there is no test, include an explanation why in the description
- [ ] Run `mvn verify` locally and all tests are passing successfully
  - It is OK to create a pull request which has failing tests if it is created as a draft, is to fix a bug and the first commit is the test to prove the existence of the bug.
- [ ] There is no new warnings (checkstyle nor spotbugs) on the code

2023-02-27 09:08 UTC, alecharp commented
I'll review the content, but first, please note that you are using part of the work from @dheerajodha from #65 without attribution of that work. I added the `help-wanted` label on that pull request because someone might want to continue the work and start from it. The branch used for #65 is located in @dheerajodha fork which is publicly available.

2023-02-27 13:48 UTC, lzeee commented
@alecharp @alecharp 
Sorry for not starting from the original branch. I have just started to understand the open source community. I mistakenly thought I can just copy the original code as basis, and mention the author's contribution in my description.

2023-03-01 11:37 UTC, alecharp requested changes
I really would have preferred that you start your work from https://github.com/dheerajodha/plugin-health-scoring/tree/feature/sort-probes as most of the work in this PR was already done by someone else.

2023-03-01 12:06 UTC, lzeee commented
> 

Ok, I will close this PR and make a fork from the original repository and make modification on that branch

I think I understand what you mean by now, because it is very unfair that the original contributor does not leave a trace of contribution.

2023-03-01 12:06 UTC, closed without merging

2023-03-01 13:24 UTC, alecharp commented
@lzeee you don't need to create a fork from @dheerajodha repository.
you can create a remote to his repository, fetch the Git data from there and checkout his branch

```
git remote add dheerajodha git@github.com:dheerajodha/plugin-health-scoring.git
git fetch dheerajodha
git switch -c feature/sort-probes dheerajodha/feature/sort-probes
```

Then you can push to your fork and create a pull request from there

```
git push -u origin feature/sort-probes
```

2023-03-01 13:31 UTC, lzeee commented
@alecharp 
Thank you very much for the detailed and patient guidance. I'm working on it now.

2023-03-01 14:05 UTC, lzeee commented on .yarnrc.yml
> +
OK, I will remove that

2023-03-01 14:06 UTC, lzeee commented on src/main/js/index.js
> +} );
Yes, it should be. I will move this code to the proper place