Add search, sort and pagination feature to probes table
jenkins-infra/plugin-health-scoring pull request #464
Opened 2024-02-13 10:11 UTC by sridamul

Closes #65 

It's been quite a long time since @dheerajodha and @lzeee tried to resolve this issue. This is a continuation of these PRs.

As mentioned by the @alecharp in this [comment](https://github.com/jenkins-infra/plugin-health-scoring/pull/222#issuecomment-1450151243), I tried to fetch the branch from @dheerajodha's repo which ultimately failed.
`git@github.com: Permission denied (publickey).`
Also the branch is too old to work on. So, I started working in a new branch (but major props to @dheerajodha and @lzeee for their contributions)

This PR replaces [datatables](https://datatables.net/) with [simple-datatables](https://github.com/fiduswriter/simple-datatables) which primarily uses plain JS instead of jquery.

Made changes according to the reviews given by @alecharp in the previous PR's. But still I have few doubts in them.

- [Comment-1](https://github.com/jenkins-infra/plugin-health-scoring/pull/109#discussion_r1022497645) 👇
> We have a package manager for front-end libraries and a build system to package everything.
This is not a working solution to me.

From my understanding and previous implementation by @lzeee , I removed the CDN of simple-database and installed the npm package of it, then abstracted the css into a separate file 'simple-datatable.less'. Do I need to change anything else?

- [Comment-2](https://github.com/jenkins-infra/plugin-health-scoring/pull/228#discussion_r1122805024) 👇
> This simple complex. Can we not have a <script> in the correct template and not have this in the global javascript?

As mentioned by @lzeee, we can use 'html-webpack-plugin' I have also researched about the alternatives but this is the most preferrable one. Suggestions are welcomed. also why don't we keep datatable function in the index.js?

Currently the probes page look like this:

https://github.com/jenkins-infra/plugin-health-scoring/assets/107404972/44e90838-deee-4aaa-a6d2-7c45d8e3d0f6

2024-02-13 10:19 UTC, sridamul commented
If possible, how can I add 'dheerajodha' and 'lzeee' as contributors to this PR?

2024-02-13 10:23 UTC, alecharp requested changes

2024-02-13 10:23 UTC, alecharp commented on core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DependabotProbe.java
> +    public static final int ORDER = AbstractDependencyBotConfigurationProbe.ORDER;
In that case, make sure to use that `ORDER` in the `@Order` class annotation.

2024-02-13 10:23 UTC, alecharp commented on core/src/main/java/io/jenkins/pluginhealth/scoring/probes/RenovateProbe.java
> +    public static final int ORDER = AbstractDependencyBotConfigurationProbe.ORDER;
Same.

2024-02-13 10:26 UTC, alecharp commented
> If possible, how can I add 'dheerajodha' and 'lzeee' as contributors to this PR?

For this, you needed to add 

```
Co-Authored-By: Username <email>
```

in your commit messages. See https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors.

It would be great to do that but it would mean to re-write your branch history and force push it. I'm usually against it but for this purpose, why not.

2024-02-13 10:32 UTC, sridamul commented
> > If possible, how can I add 'dheerajodha' and 'lzeee' as contributors to this PR?
> 
> For this, you needed to add 
> 
> ```
> Co-Authored-By: Username <email>
> ```
> 
> in your commit messages. See https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors.
> 
> It would be great to do that but it would mean to re-write your branch history and force push it. I'm usually against it but for this purpose, why not.

Right now I am moving back home, let me immediately do this after reaching home.

2024-02-14 11:07 UTC, alecharp requested changes

2024-02-14 11:07 UTC, alecharp commented on war/src/main/resources/templates/probes/listing.html
> +    <script src="" data-th-src="@{/js/index.js}" type="text/javascript"></script>
this is already included in the `layouts/main` which this page is based on.

```suggestion
```

2024-02-14 11:07 UTC, alecharp commented on war/src/main/js/index.js
> +new DataTable("#probes-table");
this means that the `DataTable` is created on all pages, even when there is no div with the correct id.
Would it be possible to only activate it on the `probes/listing.html`?

2024-02-16 15:06 UTC, alecharp commented on war/src/main/less/modules/simple-datatable.less
I'm not sure why we need to have this entire file added in the project when it should come from the dependency directly.

2024-02-16 15:08 UTC, sridamul commented on war/src/main/less/modules/simple-datatable.less
I thought it would be better to modify the design if we want in the future

2024-02-16 15:12 UTC, alecharp commented on war/src/main/less/modules/simple-datatable.less
we shouldn't need the entire file but override the classes we want.

2024-02-19 08:57 UTC, alecharp commented on war/src/main/less/index.less
> +@import '/node_modules/simple-datatables/src/css/style.css';
```suggestion
@import '~simple-datatables/src/css/style.css';
```

2024-02-26 05:33 UTC, sridamul commented
Hey @alecharp, if possible, could you please check if any more changes are required?

2024-02-28 09:12 UTC, alecharp commented
@sridamul please, do not force-push on pull request that had already been reviewed. This means I have to check everything again.

2024-03-12 14:42 UTC, alecharp commented
@sridamul I'm sorry I pushed a few commits on your pull request. This is mostly to fix issues that are checked since Spotless setup and to finish the work you have done. 

Thank you for your contribution. I'm going to merge this shortly.

2024-04-01 17:52 UTC, sridamul commented
Hey @alecharp Is it ready to ship?

2024-04-02 09:30 UTC, alecharp commented
Currently no. There are plenty of conflicts.

2024-04-24 15:15 UTC, sridamul commented
Hey @alecharp I have resolved the conflicts and the changes seems to work fine as expected.
Following are the new changes made:
- added getOrder() fn in CodeOwnershipProbe
- applied spotbugs (which is the reason to change the copyright year and alignment in some probes)

2024-04-25 08:45 UTC, alecharp commented
> sorry for applying the spotless changes in single PR

that was required of you as you changed the probe codes. However, I'm not sure it was required to do so on the unit tests. I'm looking at it.

in the end, I like the sorting and search of the probes. But the Java code changes seems a bit too big for such a little feature. I'm not questioning the pull request, just the addition of the `getOrder` method. I'm wondering if just adding the UI feature without the order couldn't be enough.

2024-04-25 13:24 UTC, sridamul commented
> I'm not questioning the pull request, just the addition of the getOrder method. I'm wondering if just adding the UI feature without the order couldn't be enough.

do you mean to drop the execution order column?

2024-04-25 13:49 UTC, alecharp commented
> do you mean to drop the execution order column?

Yes.

2024-04-25 14:29 UTC, sridamul commented
Sorry for the force push!

Here is the final table lookup...

![final_table](https://github.com/jenkins-infra/plugin-health-scoring/assets/107404972/df5ca902-cc07-44e6-bfe0-1a73a5c5a1c8)

wdyt?

2024-04-26 10:21 UTC, alecharp requested changes
> Sorry for the force push!

That's fine.

That would be great.
Could I ask of you to make sure to have the `9.0.3` version of `simple-datatables` and not use the `^` (which introduce version uncertainty). Thanks.

2024-04-26 10:21 UTC, alecharp commented on war/package.json
> +    "simple-datatables": "^9.0.0"
```suggestion
    "simple-datatables": "9.0.0"
```

2024-04-29 15:41 UTC, alecharp approved these changes
Thank you very much for your time and effort on this pull request.

2024-04-30 09:23 UTC, merged